### ISSUE TITLE
Bug in example_notebook.ipynb

### ISSUE THREAD

**Issue by st0nedB** [sreyas-mohan/DeepFreq#1]
Hi, 
upon running the ´example_notebook.ipynb´ I discovered a dimensionality bug. 
In code cell 7 
```python
with torch.no_grad():
    fr_0dB = fr_module(torch.tensor(signal_0dB[idx][None]))
    nestimate_0dB = fc_module(fr_0dB).numpy().round()
    fr_10dB = fr_module(torch.tensor(signal_10dB[idx][None]))
    nestimate_10dB = fc_module(fr_10dB).numpy().round()
    fr_50dB = fr_module(torch.tensor(signal_50dB[idx][None]))
    nestimate_50dB = fc_module(fr_50dB).numpy().round()
    
fr_0dB = fr_0dB.numpy()    
fr_10dB = fr_10dB.numpy()    
fr_50dB = fr_50dB.numpy()
```

the following Runtime error occurs, which points to a dimensionality problem IMHO:
```python
RuntimeError: size mismatch, m1: [1 x 308], m2: [200 x 1] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
```

My environment:
* numpy - version 1.18.3
* torch - version 1.5.1

As I was running the notebook to better understand the paper, I am not sure how to resolve this mismatch. Can you let me know how to fix it?
Big thank you for posting your code, btw. I really appreciate the effort. 
Looking forward to hear from you!

**Comment by sreyas-mohan** [comment]
We developed and tested the code for torch `1.1`. We checked agian with torch `1.1` and the code works without any bugs. 

We were able to reproduce the issue with torch `1.5` and we suspect that the issue is caused by padding in transpose convolution layer in the frequency representation module. We'll leave the issue open and fix it in the coming weeks. Please use the code with torch `1.1` till then. Thanks!

**Comment by WryBin** [comment]
Hello, have you solved this problem yet？

**Comment by oceanchad** [comment]
Try with
scipy==1.4.0
torch==1.4.0
python version : 3.8.6
ide: vs code

After install the dependency as above, issue should be solved.

**Comment by gizacard** [comment]
The bug comes from changes in the way circular padding works in pytorch.
I've pushed a fix that should work for different version except pytorch 1.5 and pytorch 1.6 with even kernel size (which we are not using by default).

**Comment by mknambiar** [comment]
This problem still exists. I am using google colab, uploaded the code there.  Did not change scipy, torch and python versions.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x244 and 200x1). 

Problem comes in the first invocation of the fc_module in the original post. I feel the trained model is probably outdated.

**Comment by mknambiar** [comment]
I believe the same changes needs to be made in FrequencyCountingModule (modules.py)  as was done in PSNet and FrequencyRepresentationModule. The conv_padding setting based on the torch version. 

More specifically for latest torch versions in modules.py

- the 1st conv1d layer of the FC module the padding should be equal to (kernel_in - downsampling)/2 (This should bring mat1 dimension to (1 x 200) - mat1 is referred to in my previous comment)
- The remaining layers should have padding = same

Nice if this could be confirmed.

**Comment by mknambiar** [comment]
[code changes.zip](https://github.com/sreyas-mohan/DeepFreq/files/11361264/code.changes.zip)
Have add code changes in the Frequency counting module (modules.py) to get this working with the latest pytorch. Plus some minor changes to test.py

**Comment by E1nzbern** [comment]
> [code changes.zip](https://github.com/sreyas-mohan/DeepFreq/files/11361264/code.changes.zip) Have add code changes in the Frequency counting module (modules.py) to get this working with the latest pytorch. Plus some minor changes to test.py

This solved my problem perfectly. Thank you very much for sharing.❤
